try{
    console.log(" this is the try block")
}
catch(error) {
    console.log("error is the "+error);
}
finally {

    console.log('finally block is always excuted')

}


